import { getAccessToken } from './firebase.ts';

// Helper for authorized fetch
async function authFetch(url: string, options: RequestInit = {}) {
  const token = await getAccessToken();
  if (!token) {
    throw new Error('Please sign in with Google to use Workspace features.');
  }

  const headers = new Headers(options.headers || {});
  headers.set('Authorization', `Bearer ${token}`);
  if (!headers.has('Content-Type') && options.body && typeof options.body === 'string') {
    headers.set('Content-Type', 'application/json');
  }

  const response = await fetch(url, {
    ...options,
    headers,
  });

  if (!response.ok) {
    const errorText = await response.text();
    let errorMsg = `Google Workspace API error (${response.status}): ${response.statusText}`;
    try {
      const parsed = JSON.parse(errorText);
      if (parsed.error?.message) {
        errorMsg = parsed.error.message;
      }
    } catch {
      if (errorText) errorMsg = errorText;
    }
    throw new Error(errorMsg);
  }

  return response.json();
}

// 1. Google Drive APIs
export interface DriveFile {
  id: string;
  name: string;
  mimeType: string;
  webViewLink?: string;
  modifiedTime?: string;
  iconLink?: string;
}

export async function listDriveFiles(query = "trashed = false", pageSize = 15): Promise<DriveFile[]> {
  const params = new URLSearchParams({
    q: query,
    pageSize: pageSize.toString(),
    fields: 'files(id, name, mimeType, webViewLink, modifiedTime, iconLink)',
    orderBy: 'modifiedTime desc',
  });
  const data = await authFetch(`https://www.googleapis.com/drive/v3/files?${params.toString()}`);
  return data.files || [];
}

export async function createDriveTextFile(name: string, content: string, mimeType = 'text/plain') {
  const token = await getAccessToken();
  if (!token) throw new Error('Not signed in');

  const boundary = '-------314159265358979323846';
  const delimiter = "\r\n--" + boundary + "\r\n";
  const closeDelim = "\r\n--" + boundary + "--";

  const metadata = {
    name,
    mimeType,
  };

  const multipartRequestBody =
    delimiter +
    'Content-Type: application/json; charset=UTF-8\r\n\r\n' +
    JSON.stringify(metadata) +
    delimiter +
    `Content-Type: ${mimeType}\r\n\r\n` +
    content +
    closeDelim;

  const response = await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': `multipart/related; boundary="${boundary}"`,
    },
    body: multipartRequestBody,
  });

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`Drive upload failed: ${err}`);
  }

  return response.json();
}

// 2. Google Sheets APIs
export async function createSEOSpreadsheet(title: string, headers: string[], rows: (string | number)[][]) {
  const token = await getAccessToken();
  if (!token) throw new Error('Not signed in');

  // Step 1: Create sheet
  const createRes = await authFetch('https://sheets.googleapis.com/v4/spreadsheets', {
    method: 'POST',
    body: JSON.stringify({
      properties: {
        title,
      },
      sheets: [
        {
          properties: {
            title: 'SEO Data',
            gridProperties: {
              frozenRowCount: 1,
            },
          },
        },
      ],
    }),
  });

  const spreadsheetId = createRes.spreadsheetId;

  // Step 2: Populate values
  const values = [headers, ...rows];
  await authFetch(
    `https://sheets.googleapis.com/v4/spreadsheets/${spreadsheetId}/values/SEO Data!A1:append?valueInputOption=USER_ENTERED`,
    {
      method: 'POST',
      body: JSON.stringify({
        values,
      }),
    }
  );

  return {
    spreadsheetId,
    spreadsheetUrl: createRes.spreadsheetUrl || `https://docs.google.com/spreadsheets/d/${spreadsheetId}`,
  };
}

// 3. Google Docs APIs
export async function createSEODocument(title: string, bodyText: string) {
  // Step 1: Create empty doc
  const doc = await authFetch('https://docs.googleapis.com/v1/documents', {
    method: 'POST',
    body: JSON.stringify({
      title,
    }),
  });

  const documentId = doc.documentId;

  // Step 2: Insert text
  if (bodyText) {
    await authFetch(`https://docs.googleapis.com/v1/documents/${documentId}:batchUpdate`, {
      method: 'POST',
      body: JSON.stringify({
        requests: [
          {
            insertText: {
              location: {
                index: 1,
              },
              text: bodyText + '\n\n— Generated by SEO Ustaad LMS',
            },
          },
        ],
      }),
    });
  }

  return {
    documentId,
    documentUrl: `https://docs.google.com/document/d/${documentId}/edit`,
  };
}

// 4. Gmail APIs
export async function sendGmailSummary(recipientEmail: string, subject: string, bodyText: string) {
  const token = await getAccessToken();
  if (!token) throw new Error('Not signed in');

  const utf8Subject = `=?utf-8?B?${btoa(unescape(encodeURIComponent(subject)))}?=`;
  const messageParts = [
    `To: ${recipientEmail}`,
    'Content-Type: text/plain; charset=utf-8',
    'MIME-Version: 1.0',
    `Subject: ${utf8Subject}`,
    '',
    bodyText,
  ];
  const message = messageParts.join('\r\n');

  // URL-safe base64 encoding
  const encodedMessage = btoa(unescape(encodeURIComponent(message)))
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');

  return authFetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send', {
    method: 'POST',
    body: JSON.stringify({
      raw: encodedMessage,
    }),
  });
}

// 5. Google Tasks APIs
export interface TaskList {
  id: string;
  title: string;
}

export interface GoogleTaskItem {
  id: string;
  title: string;
  status: 'needsAction' | 'completed';
  due?: string;
  notes?: string;
}

export async function listTaskLists(): Promise<TaskList[]> {
  const data = await authFetch('https://tasks.googleapis.com/tasks/v1/users/@me/lists');
  return data.items || [];
}

export async function listTasks(taskListId = '@default'): Promise<GoogleTaskItem[]> {
  const data = await authFetch(`https://tasks.googleapis.com/tasks/v1/lists/${taskListId}/tasks`);
  return data.items || [];
}

export async function createGoogleTask(taskListId = '@default', title: string, notes?: string) {
  return authFetch(`https://tasks.googleapis.com/tasks/v1/lists/${taskListId}/tasks`, {
    method: 'POST',
    body: JSON.stringify({
      title,
      notes: notes || 'Synced from SEO Ustaad Daily Study Plan',
      status: 'needsAction',
    }),
  });
}

// 6. Google Classroom APIs
export interface ClassroomCourse {
  id: string;
  name: string;
  section?: string;
  descriptionHeading?: string;
  alternateLink?: string;
  courseState?: string;
}

export interface ClassroomCourseWork {
  id: string;
  title: string;
  description?: string;
  alternateLink?: string;
  dueDate?: { year: number; month: number; day: number };
  maxPoints?: number;
}

export async function listClassroomCourses(): Promise<ClassroomCourse[]> {
  const data = await authFetch('https://classroom.googleapis.com/v1/courses?courseStates=ACTIVE');
  return data.courses || [];
}

export async function listClassroomCourseWork(courseId: string): Promise<ClassroomCourseWork[]> {
  const data = await authFetch(`https://classroom.googleapis.com/v1/courses/${courseId}/courseWork`);
  return data.courseWork || [];
}

export async function createClassroomAnnouncement(courseId: string, text: string) {
  return authFetch(`https://classroom.googleapis.com/v1/courses/${courseId}/announcements`, {
    method: 'POST',
    body: JSON.stringify({
      text,
      state: 'PUBLISHED',
    }),
  });
}
